ecplipse = str

meu_dicionario = {
    "orb comun": "uso 1",
    "orb imcomun": "uso 2",
    "orb raro": "uso 2",
    "orb ultrararo": "uso 3",
    "orb do evento": "uso 1",
    "orb concentrado": "uso 1",
    "orb das conecxoes": "uso 1",
    "orb da rotação infinita": "uso sem limites,",
    "orb cristalizador": "uso 1",
    "orb concentrado das trevas": "uso 1",
    "orb do heroi": "uso 1",
    "orb mutante": "uso 1",
    "orb mutante ultra celular": "uso 1",
    "orb nuclear mega concentrado aprisionativo": "uso 1",
    "orb da froça !!!": "uso 1",
    "orb da força@": "uso 1",
    "orb do eclipse": "Só pode ser usado duranto o {eclipse}",
    "orb da divisão": "uso 1",
    "orb do amor": "uso 2",
    "orb requien": "uso 1",
    "orb dos 5": "uso 1",
    "orb da troca de sexo": "uso 1",
    "orb da guera": "uso 1",
    "orb selo do poder": "uso 1",
    "orb inverso": "uso ilimitado",
    "orb cosmico": "uso 1",
    "orb do LULA": "uso 1",
    "barras de ferro": "por quantdade",
    "baterias": "quantidade e porcentagen",
}
