ecplipse = str

meu_inventario = {
    "orb comun": "uso 1",
    "orb imcomun": "uso 2",
    "orb raro": "uso 2",
    "orb ultrararo": "uso 3",
    "orb do evento": "uso 1",
    "orb concentrado": "uso 1",
    "orb das conecxoes": "uso 1",
    "orb da rotação infinita": "uso sem limites,",
    "orb cristalizador": "uso 1",
    "orb concentrado das trevas": "uso 1",
    "orb do heroi": "uso 1",
    "orb mutante": "uso 1",
    "orb mutante ultra celular": "uso 1",
    "orb nuclear mega concentrado aprisionativo": "uso 1",
    "orb da froça !!!": "uso 1",
    "orb da força@": "uso 1",
    "orb do eclipse": "Só pode ser usado durante o {eclipse}",
    "orb da divisão": "uso 1",
    "orb do amor": "uso 2",
    "orb requien": "uso 1",
    "orb dos 5": "uso 1",
    "orb da troca de sexo": "uso 1",
    "orb da guera": "uso 1",
    "orb selo do poder": "uso 1",
    "orb inverso": "uso ilimitado",
    "orb cosmico": "uso 1",
    "orb do LULA": "uso 1",
    "barras de ferro": "por quantdade",
    "baterias": "quantidade e porcentagen",
    "Lança da magia": "dano 30, torna o uso de magias sem gasto",
    "capacete da percepção": " inteligencia magia e sorte x3 e sanidade sempra acima de 3",
    "Canhão de matera escura": "dano 600 Precisão 70" "sem limties de uso",
    "gerador de mini bots 0": "sem taxa de uso",
    "armadura DC4": "Duração 100, é capaz de viajar entre dimençoes",
    "armadura da rotação": "Duração 200 ao ser atingida trancende ao poder ou o golpe por um turno",
    "armadura da navegação a distancia": "Duração 300, se quem estiver usando a armadura atirar um projeto energetico a armadura possibiliatra alcançar o alvo ou criar uma passagen dimensional a ele",
    "armadura comun": "Duração 300",
    "armadura climatica": "Duração 400",
    "armadura de combate 1": "Duração 500",
    "armadura voadora": "Duração 600, é capaz de voar",
    "Nulceo nivel 1": "Fonte de energia para construçoes",
    "Nucleo nivel 2": "Fonte de energia para cidades",
    "Vibranio": "minerio",
    "arma laizer tec": "Dano 200 preicisão 200",
    "arma laizer tec1": "Dano 300 preicisão 300",
    "Bateria de cardiohumana": "usada apenas em seres vivos",
    "Bateria espiritual das trevas ": "usada para entidades e espiritos das trevas",
    "Bateria liquida50": "Uso multfuncional",

}
